apiVersion: v1
kind: Namespace
metadata:
  name: yfcc

---

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: yfcc
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: yfcc
spec:
  commonName: yfcc.in
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: yfcc-ingress
  namespace: yfcc
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts: 
    - yfcc.in
    secretName: selfsigned-cert-tls
  rules:
  - host: yfcc.in 
    http:
      paths:
      - path: /
        backend:
          serviceName: yfcc-cert-svc
          servicePort: 80
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yfcc
  namespace: yfcc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yfcc
  template:
    metadata:
      labels:
        app: yfcc
    spec:
      containers:
      - name: yfcc
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: yfcc-cert-svc
  namespace: yfcc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: yfcc
